import re

with open('compiler/frontend/parser.py', 'r') as f:
    content = f.read()
    
content = re.sub(r'value in \["number", "string", "bool", "list", "dict", "result"\]', 'value in ["lala_number", "lala_string", "lala_bool", "lala_list", "lala_dict", "lala_result"]', content)
content = content.replace('"agar"', '"lala_agar"')
content = content.replace('"warna_agar"', '"lala_warna_agar"')
content = content.replace('"warna"', '"lala_warna"')
content = content.replace('"jabtak"', '"lala_jabtak"')
content = content.replace('"loop"', '"lala_loop"')
content = content.replace('"har"', '"lala_har"')
content = content.replace('"in"', '"lala_in"')
content = content.replace('"roko"', '"lala_roko"')
content = content.replace('"agla"', '"lala_agla"')
content = content.replace('"lautao"', '"lala_lautao"')
content = content.replace('"kaam"', '"lala_kaam"')
content = content.replace('"varg"', '"lala_varg"')
content = content.replace('"swaroop"', '"lala_swaroop"')
content = content.replace('"laao"', '"lala_laao"')
content = content.replace('"bahar"', '"lala_bahar"')
content = content.replace('"panic"', '"lala_panic"')
content = content.replace('"result"', '"lala_result"')
content = content.replace('"match"', '"lala_match"')
content = content.replace('"Expected \'laao\'"', '"Expected \'lala_laao\'"')
content = content.replace('"Expected \'kaam\'"', '"Expected \'lala_kaam\'"')
content = content.replace('"Expected \'varg\'"', '"Expected \'lala_varg\'"')
content = content.replace('"Expected \'swaroop\'"', '"Expected \'lala_swaroop\'"')
content = content.replace('"Expected \'agar\'"', '"Expected \'lala_agar\'"')
content = content.replace('"Expected \'jabtak\'"', '"Expected \'lala_jabtak\'"')
content = content.replace('"Expected \'loop\'"', '"Expected \'lala_loop\'"')
content = content.replace('"Expected \'har\'"', '"Expected \'lala_har\'"')
content = content.replace('"Expected \'roko\'"', '"Expected \'lala_roko\'"')
content = content.replace('"Expected \'agla\'"', '"Expected \'lala_agla\'"')
content = content.replace('"Expected \'lautao\'"', '"Expected \'lala_lautao\'"')
content = content.replace('"Expected \'match\'"', '"Expected \'lala_match\'"')

with open('compiler/frontend/parser.py', 'w') as f:
    f.write(content)
